---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      version: 0.13.9
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 10m
  values:
    crds:
      enabled: false
    prometheus:
      serviceMonitor:
        enabled: "What if this is the value of the value string"
...
