---
# 1 Top level map with key value
apiVersion: networking.k8s.io/v1
kind: Ingress # some stuff here
metadata:
  # 2 Indented object key
  annotations:
    # 3 indented map with key value
    cert-manager.io/cluster-issuer: acme # This will attempt to automatically generate a cert.
    acme.cert-manager.io/http01-edit-in-place: "true" # This makes the HTTP01 handler more robust.
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
  labels:
    app: uxguide-site
  name: uxguide-site
  namespace: uxguide
spec:
  ingressClassName: "nginx"
  rules: # This shouldn't be here
  # 4 array with key value
    - host: uxguide-temp.k8s.epic.com # What about this
      http:
        paths:
          # 5 Array object key
          - backend: # some stuff
              service:
                name: uxguide-site # This needs to match an existing service name in the same namespace as this ingress
                port:
                  name: webhttp # This needs to match an existing port name in this service
            path: /
            pathType: Prefix
    - host: uxguide-temp.k8s.epic.com # some other stiff
      http:
        paths:
          - backend:
              service:
                name: uxguide-site # This needs to match an existing service name in the same namespace as this ingress
                port:
                  name: webhttp # This needs to match an existing port name in this service
            path: /
            pathType: Prefix
  tls: # The list of hosts needs to match the rules above for ACME to work
    - hosts:
      # 6 Array value only
        - uxguide-temp.k8s.epic.com
      secretName: "What happens when you make a quoted string" # also a comment
