apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.uxguide-site.yaml
patches:
- target:
    group: networking.k8s.io  
    version: v1
    kind: Ingress
    name: uxguide-site
  patch: |-
    - op: replace
      path: /metadata/annotations/acme.cert-manager.io~1http01-edit-in-place
      value: something.cool
    - op: replace
      path: /spec/rules/1/http/paths/0/pathType
      value: something.cool

